sudo: false

env:
  global:
    secure: kRjum2tZsaQZPnti27bc/ZIjYS1hftXTyuSWdq/6raRignORgbZMUc/RMXBz+ig8kiEVE3SFBZdapECGj+3Vb6Q6Vi4ypv8lR4rtJMTNITSOeM1KHHDCi6xLLGKrOsJ5ndkYHTNxuyIMGZu9Sv3TMcNqHcBChbZKT383OXgrxLA=

matrix:
  include:
  - os: osx
    language: generic
    env: PYTHON=python2 ENABLE_LIBSPHINXAD=1 BUILD_WHEEL=true
  - os: osx
    language: generic
    env: PYTHON=python3 ENABLE_LIBSPHINXAD=1 BUILD_WHEEL=true
  - os: linux
    language: python
    python: 2.7
    env: PYTHON=python2 ENABLE_LIBSPHINXAD=1
  - os: linux
    language: python
    python: 3.5
    env: PYTHON=python3 ENABLE_LIBSPHINXAD=1
  - os: linux
    language: python
    python: 3.6
    env: PYTHON=python3 ENABLE_LIBSPHINXAD=1 BUILD_SDIST=true

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig python python@2; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --overwrite python; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link --overwrite python@2; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y swig libpulse-dev; fi

install:
  - $PYTHON -m pip install --upgrade pip setuptools wheel twine

script:
  - $PYTHON setup.py test

before_deploy:
  - if [[ "$BUILD_SDIST" == "true" ]]; then $PYTHON setup.py sdist; fi
  - if [[ "$BUILD_WHEEL" == "true" ]]; then $PYTHON setup.py bdist_wheel; fi

deploy:
  provider: script
  script: twine upload -u bambucha -p $PASSWORD dist/*
  on:
    tags: true
    branch: master
    condition: '"$BUILD_SDIST" == "true" || "$BUILD_WHEEL" == "true"'
  skip_cleanup: true
