language: python
sudo: false

env:
  matrix:
    - ENABLE_LIBSPHINXAD=1
  global:
    secure: kRjum2tZsaQZPnti27bc/ZIjYS1hftXTyuSWdq/6raRignORgbZMUc/RMXBz+ig8kiEVE3SFBZdapECGj+3Vb6Q6Vi4ypv8lR4rtJMTNITSOeM1KHHDCi6xLLGKrOsJ5ndkYHTNxuyIMGZu9Sv3TMcNqHcBChbZKT383OXgrxLA=

matrix:
  include:
  - os: osx
    python: 2.7
  - os: osx
    python: 3.5
  - os: osx
    python: 3.6
  - os: linux
    python: 2.7
  - os: linux
    python: 3.5
  - os: linux
    python: 3.6
    env: BUILD_SDIST=true ENABLE_LIBSPHINXAD=1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install swig; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y swig libpulse-dev; fi

install:
  - python -m pip install --upgrade pip setuptools wheel twine

script:
  - python setup.py test

before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python setup.py bdist_wheel; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$BUILD_SDIST" == "true" ]]; then python setup.py sdist; fi

deploy:
  provider: script
  script: twine upload -u bambucha -p $PASSWORD dist/*
  on:
    tags: true
    branch: master
  skip_cleanup: true
