version: 0.1.7 ({build})

environment:
  password:
    secure: KZdEfjKCVSUL334LJP/iPqWKfzhoIm43D4VZwJcEb0k=

  matrix:
    - PYTHON: C:\Python27
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
      VCVARSALLARCH: x86
    - PYTHON: C:\Python35
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
      VCVARSALLARCH: x86
    - PYTHON: C:\Python36
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
      VCVARSALLARCH: x86
    - PYTHON: C:\Python27-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
      VCVARSALLARCH: x64
    - PYTHON: C:\Python35-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
      VCVARSALLARCH: x64
    - PYTHON: C:\Python36-x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      VCVARSALLPATH: C:\"Program Files (x86)\Microsoft Visual Studio 14.0"\VC\vcvarsall.bat
      VCVARSALLARCH: x64

init:
  - call %VCVARSALLPATH% %VCVARSALLARCH%
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - git submodule update --init --recursive
  - choco install -y swig
  - python -m pip install --upgrade pip setuptools wheel twine

build: off

test_script:
  - python setup.py test

after_test:
  - python setup.py bdist_wheel
  - python setup.py bdist_wininst
  - python setup.py bdist_msi

artifacts:
  - path: dist/*

on_success:
  - ps: if ($env:appveyor_repo_tag -eq $true) {twine upload -u bambucha -p $env:password dist/*}
