version: 0.1.7 ({build})

environment:
  password:
    secure: KZdEfjKCVSUL334LJP/iPqWKfzhoIm43D4VZwJcEb0k=

  matrix:
    - PYTHON: C:\Python27
    - PYTHON: C:\Python35
    - PYTHON: C:\Python36
    - PYTHON: C:\Python27-x64
    - PYTHON: C:\Python35-x64
    - PYTHON: C:\Python36-x64

init:
  - reg delete "HKLM\Software\Wow6432Node\Microsoft\VisualStudio\9.0\Setup\VC\ProductDir" /f
  - reg delete "HKLM\Software\Wow6432Node\Microsoft\VCExpress\9.0\Setup\VC\ProductDir" /f
  - reg delete "HKLM\Software\Microsoft\VisualStudio\9.0\Setup\VC\ProductDir" /f
  - reg delete "HKLM\Software\Microsoft\VCExpress\9.0\Setup\VC\ProductDir" /f
  - set VS90COMNTOOLS=%VS140COMNTOOLS%
  - set PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%

install:
  - git submodule update --init --recursive
  - choco install -y swig
  - python -m pip install --upgrade pip setuptools wheel twine

build: off

test_script:
  - python setup.py test

after_test:
  - python setup.py bdist_wheel
  - python setup.py bdist_wininst
  - python setup.py bdist_msi

artifacts:
  - path: dist/*

on_success:
  - ps: if ($env:appveyor_repo_tag -eq $true) {twine upload -u bambucha -p $env:password dist/*}
