version: 0.1.7 ({build})

environment:
  password:
    secure: KZdEfjKCVSUL334LJP/iPqWKfzhoIm43D4VZwJcEb0k=

  matrix:
    - python: C:/Python27/python.exe
      twine: C:/Python27/Scripts/twine.exe
    - python: C:/Python35/python.exe
      twine: C:/Python35/Scripts/twine.exe
    - python: C:/Python36/python.exe
      twine: C:/Python36/Scripts/twine.exe
    - python: C:/Python27-x64/python.exe
      twine: C:/Python27-x64/Scripts/twine.exe
    - python: C:/Python35-x64/python.exe
      twine: C:/Python35-x64/Scripts/twine.exe
    - python: C:/Python36-x64/python.exe
      twine: C:/Python36-x64/Scripts/twine.exe

install:
  - ps: git submodule update --init --recursive
  - ps: $env:python -m pip install --upgrade pip setuptools wheel twine
  - ps: choco install -y swig

build: off

test_script:
  - ps: $env:python setup.py test

after_test:
  - ps: $env:python setup.py bdist_wheel
  - ps: $env:python setup.py bdist_wininst
  - ps: $env:python setup.py bdist_msi

artifacts:
  - path: dist/*

on_success:
  - ps: if ($env:appveyor_repo_tag -eq $true) {$env:twine upload -u bambucha -p %password% dist/*}
